### ISSUE TITLE
FilePondPluginImageTransform hangs on safari iPhone x and above model

### ISSUE THREAD

**Issue by weijiegh** [pqina/filepond-plugin-image-transform#6] opened 2019-04-24 13:20 UTC
You can reproduce it using sample code from here: 
https://github.com/pqina/react-filepond/blob/master/example/src/App.js

1. Add filepond-plugin-image-resize and filepond-plugin-image-transform
2. Change the sample code to add two more properties: 
                        imageResizeTargetWidth="200"
                        imageResizeTargetHeight="200"
3. Run the sample code,  use iPhone  x and above model to browse to the url with "Safari" and try to upload a picture, it will hang forever with status "Uploading...".
 
This is the final FilePond object:

```jsx
 <FilePond ref={ref => this.pond = ref}
        files={this.state.files}
        allowMultiple={true}
        imageResizeTargetWidth="200"
        imageResizeTargetHeight="200"
        server={{
            // fake server to simulate loading a 'local' server file and processing a file
            process: (fieldName, file, metadata, load) => {
                // simulates uploading a file
                setTimeout(() => {
                    load(Date.now())
                }, 1500);
            },
            load: (source, load) => {
                console.log(source);
                console.log(load);
                // simulates loading a file from the server
                fetch(source)
                .then(res => { console.log(res); return res.blob();})
                .then((blob) =>{console.log(blob); return load(blob);});
            }
        }}
        oninit={() => this.handleInit() }
        onupdatefiles={fileItems => {
            // Set currently active file objects to this.state
            this.setState({
                files: fileItems.map(fileItem => fileItem.file)
            });
        }}>
</FilePond>
```

**Comment by rikschennink** [comment] 2019-04-29 09:04
I just tested this in the iPhone X Simulator and it seems to run correctly. The problem might be located somewhere else.

![Screenshot 2019-04-29 at 11 03 40](https://user-images.githubusercontent.com/1132575/56886135-89103b80-6a6e-11e9-8571-a1a6fe475e3f.png)

**Comment by weijiegh** [comment] 2019-05-10 17:48
I tested using browserstack with real device iPhone X, browser Safari, it hangs on uploading forever:

![image](https://user-images.githubusercontent.com/33634778/57546140-1898d280-732a-11e9-9c38-942f3711dc4d.png)

**Comment by rikschennink** [comment] 2019-05-11 17:32
Just tested on BrowserStack as well, just to be sure. Don't have time right now to test the React version, but the normal one works as intended. Can you make a reproduction of the issue on [codesandbox](https://codesandbox.io/s/github/KimGenius/React-file-pond)?

**Comment by weijiegh** [comment] 2019-05-11 23:41
Did you use Safari in your testing? Your picture's cut off, I just want to make sure.

I created a codesandbox here: https://codesandbox.io/s/yq84poxwk1. I ran it in iPhone X safari in browserstack, same issue.

**Comment by rikschennink** [comment] 2019-05-12 05:50
Yes that’s Safari, will test the sandbox on Monday.

**Comment by rikschennink** [comment] 2019-05-13 06:40
![Screenshot 2019-05-13 at 08 39 18](https://user-images.githubusercontent.com/1132575/57600634-a6f39b00-755a-11e9-8faf-76cb5370a973.png)

**Comment by weijiegh** [comment] 2019-05-14 17:17
I am not sure why it works for you. This is how I tested it:
1. Open the iPhone X and go straight to Safari. If you keep switching Chrome and Safari, it will somehow start working.
2. Paste the URL, and then try to upload a picture, it will hang. I also tried your demo URL and got the same problem: https://pqina.github.io/filepond-plugin-image-transform/.

![image](https://user-images.githubusercontent.com/33634778/57718105-991d4300-764a-11e9-90ec-18115d243f60.png)

**Comment by rikschennink** [comment] 2019-05-17 05:49
I will test again next week.

**Comment by rikschennink** [comment] 2019-05-21 06:23
Tried just now. The demo on https://pqina.github.io/filepond-plugin-image-transform/ shows the output image correctly.

I'm going to close this as I can't reproduce it.

**Closed by rikschennink** 2019-05-21 06:23 UTC

**Comment by denisraison** [comment] 2020-05-06 05:09
Hi @weijiegh 

Did you find a solution for it?
I'm running on the same issue with iOS 12...

It's hanging on waiting for size forever after taking a picture, it works fine if I choose an image from the gallery but it fails when taking a picture straight from the browser...

Cheers,

**Comment by denisraison** [comment] 2020-05-06 05:53
Hi @rikschennink 

I've found that using the latest available version (2.0.5) for the filepond-plugin-image-resize plugin and setting the imageResizeTargetWidth to anything causes the issue.

**Comment by rikschennink** [comment] 2020-05-06 06:08
@denisraison this also happens in the demo linked above?

And if so, which device are you testing with and what image size are you adding?

**Comment by denisraison** [comment] 2020-05-06 22:21
Hi @rikschennink 

Yes, it does happen with the demo link above.

The issue with isn't specifically with the image-transform it's with the image-resize... and only when you take a new picture from the camera directly from filepond. The resize works fine when selecting an image from the library.

We had to downgrade the filepond-plugin-image-resize back to version 2.0.4...

Thanks,

**Comment by rikschennink** [comment] 2020-05-07 09:04
@denisraison thanks for the additional details, will run some tests

**Comment by rikschennink** [comment] 2020-05-08 06:09
@denisraison can you give version 2.0.6 of the plugin a try?

**Comment by denisraison** [comment] 2020-05-11 22:39
Hi @rikschennink ,

I've just tested it running the version 2.0.6 and looks like it's working just fine.

Thanks for the update, I appreciate.
